### PR TITLE
avira windows (code borrowed from y0ug)

### PR DESCRIPTION
**Pull request by kamino**
@y0ug are you OK if we take your code as basis for a avira probe in IRMA ? you should keep ownership of the commits, but some of them are going to be squashed.

### CODE REVIEW

**Comment by y0ug** [comment]
No problem for me. I can rebase the code if you need.

PS: I didn't test the code since January

**Comment by turbo420** [comment]
how did you set this up?? did you use Avira free and the command line scanner. i try to setup the Avira command line scanner and it didn't work because of the key.

**Comment by y0ug** [comment]
Hi have doc this on:
https://github.com/y0ug/irma-probe-vagrant-win/blob/master/docs/avira.md

**Comment by turbo420** [comment]
nice work y0ug ;)

**Comment by ch0k0bn** [comment]
this work great, just fixed get_version typo. Good jobs guys

**Pull request merged**
